---
name: cia01
# creating github action 

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

      - name: Checkout source
        uses: actions/checkout@v4

##      - name: Install kind
##        uses: helm/kind-action@v1.9.0
##        with:
##          version: v0.23.0
##          node_image: kindest/node:v1.29.2

      - name: Deploy to cluster
        run: |
          kubectl apply -f pod.yml
      
