---
name: cia01
# creating github action 

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:   # ðŸ‘ˆ this enables the manual trigger

jobs:
  deploy:
    runs-on: self-hosted
## above will run from local runner & below -ubuntu- will run from the HELM
#    runs-on: ubuntu-latest

    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

      - name: Checkout source
        uses: actions/checkout@v4

###   THIS SECTION IS NEEDED, IF THE KUBE CLUSTER HAS TO BE CREATED WITHIN THE HELM IF YES, THEN 
###   THE NEW POD WILL NOT BE CREATED IN THE LOCAL MACHINE, INSTEAD IT WILL CREATED IN THE HELP CLUSTER
##      - name: Install kind
##        uses: helm/kind-action@v1.9.0
##        with:
##          version: v0.23.0
##          node_image: kindest/node:v1.29.2

      - name: Deploy to cluster
        run: |
          kubectl apply -f pod.yml
      
